# Generated by Django 3.1.5 on 2021-05-01 09:00

from django.db import migrations, models
import django.db.models.deletion
import polls.validates


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'completed poll',
                'verbose_name_plural': 'completed polls',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('date_start', models.DateTimeField(verbose_name='date start')),
                ('date_finish', models.DateTimeField(verbose_name='date finish')),
            ],
            options={
                'verbose_name': 'poll',
                'verbose_name_plural': 'polls',
                'ordering': ('-date_start',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.PositiveIntegerField(default=0, verbose_name='sorting')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('question_type', models.CharField(choices=[('text', 'text'), ('choice', 'choice'), ('multiple choice', 'multiple choice')], max_length=50, validators=[polls.validates.validateQuestionType], verbose_name='question type')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='poll')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('sorting',),
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='answer')),
                ('completed_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.completedpoll', verbose_name='completed poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'user answer',
                'verbose_name_plural': 'user answers',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OptionTheQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.PositiveIntegerField(default=0, verbose_name='sorting')),
                ('option_text', models.TextField(verbose_name='option text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'option the question',
                'verbose_name_plural': 'options the questions',
                'ordering': ('sorting',),
            },
        ),
        migrations.AddField(
            model_name='completedpoll',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='poll'),
        ),
    ]
