# Generated by Django 3.1.5 on 2021-05-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionthequestion',
            name='option_true',
            field=models.BooleanField(default=False, verbose_name='option true'),
        ),
    ]
